LeagueHistory/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using LeagueHistory.Models;
using Newtonsoft.Json;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using RiotSharp;
using RiotSharp.Misc;
using System.Linq;
using System.IO;

using LeagueHistory.Models.myClass;
using RiotSharp.Endpoints.SummonerEndpoint;

namespace LeagueHistory.Controllers
{
    public class HomeController : Controller
    {
        private static ApiStructure apiStructure = new ApiStructure();
        private string ApiKey = apiStructure.GetApiRiot();
        public static string[] champions = LeagueChampionsAbilities.champions;
        public static string[] SummonerSpell = LeagueChampionsAbilities.summonerSpells;
        // GET: Home

        public async Task<ActionResult> Index()
        {

            return View();
            return RedirectToAction("Index", "ChampionAvgDB");

         
        }



        [HttpPost]
        public async Task<ActionResult> DisplayAccount(string selectedRegion, string user, int historyNumber)
        {
        
            var api = RiotApi.GetDevelopmentInstance(ApiKey);
            SummonerV4 UserInfo = new SummonerV4();
            List<MyViewModel> viewModel = new List<MyViewModel>();

            

            try
            {
                var summoner = api.Summoner.GetSummonerByNameAsync(Region.Euw, user).Result;

                UserInfo.accountId = summoner.AccountId;
                var bruh = api.ChampionMastery.GetChampionMasteryAsync(Region.Euw, summoner.AccountId, 99);

                viewModel = await GetMatchAsync(Region.Euw, UserInfo.accountId, historyNumber);
            }
            catch (RiotSharpException ex)
            {
                // Handle the exception however you want.
            }
            var temp = viewModel;

            ViewBag.AmmountOfGames = (historyNumber);

            return View(viewModel);
        }

        public async Task<List<MyViewModel>> GetMatchAsync(Region region, string AccountId, int matchAmmount)
        {
            var api = RiotApi.GetDevelopmentInstance(ApiKey);

            List<MatchHistory> ListOfMatch = new List<MatchHistory>();
            List<matchParticipant> TempListOfGame = new List<matchParticipant>();
            List<matchParticipant> ListOfGame = new List<matchParticipant>();

            var matches = api.Match.GetMatchListAsync(Region.Euw, AccountId).Result;


            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://ddragon.leagueoflegends.com/cdn/10.11.1/data/en_US/champion.json");

            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));

            for (int i = 0; i < matchAmmount; i++)
            {
                ListOfMatch.Add(new MatchHistory()
                {
                    lane = matches.Matches[i].Lane.ToString(),
                    champion = Convert.ToInt32(matches.Matches[i].ChampionID),
                    season = Convert.ToInt32(matches.Matches[i].Season),
                    role = matches.Matches[i].Role.ToString(),
                    platformId = matches.Matches[i].PlatformID.ToString(),
                    gameId = matches.Matches[i].GameId,
                    queue = matches.Matches[i].Queue
                });

                TempListOfGame = await GetMatchParticipantsItemsAsync(ListOfMatch[i].gameId, AccountId); //gör en statisk lista om håller kvar alla matcher? eller ett objekt lista?
                //public async Task<List<championItemList>> GetMatchSummonerSpells(List<championItemList> championItemLists)
               
                ListOfGame.Add(new matchParticipant()
                {
                    gameParticipants = TempListOfGame[0].gameParticipants
                }); 
                
                //Index Must be 0. since the call only collects 1 call at time. FIX   //ToDo. Find solution to call function, collect all games and return a full list. Try to make it into only 1 call.
                     //Solution might be to create a list of ListOfMatch and select all gameId and send it? Look into this
                HttpResponseMessage response = await client.GetAsync("http://ddragon.leagueoflegends.com/cdn/10.11.1/data/en_US/champion.json").ConfigureAwait(false);
                if (response.IsSuccessStatusCode)
                {
                    dynamic jsonObject = await response.Content.ReadAsStringAsync();
                    Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(jsonObject);
                    var data = myDeserializedClass.data;

                    foreach (var champion in champions)
                    {
                        var property = data.GetType().GetProperty(champion);
                        var propertyValue = property.GetValue(data) as charInfo;

                        foreach (var champ in ListOfMatch)
                        {
                            if (champ.champion == Convert.ToInt32(propertyValue.key))
                            {
                                champ.championName = propertyValue.name;
                                
                                //  return champ.championName.FirstOrDefault();  #ToDo. Gör en first or defualt
                            }
                            if (champ.championName == null)
                            {
                                champ.championName = champ.champion.ToString();
                            }
                        }

                    }

                }
            }
            List<MyViewModel> viewModel = new List<MyViewModel>();

            viewModel.Add(new MyViewModel()
            {
                TheFirstTable = ListOfGame,
                TheSecondTable = ListOfMatch
            });

            return viewModel;
        }

        public async Task<List<matchParticipant>> GetMatchParticipantsItemsAsync(long matchId, string accountId)
        {
            var counter = 0;

            List<championItemList> teamChamptionItemList = new List<championItemList>();
            List<championItemList> TempList = new List<championItemList>();


            List<championItemList> singelChampionItemList = new List<championItemList>();
            List<SumParticipant> participants = new List<SumParticipant>();
            List<matchParticipant> funka1 = new List<matchParticipant>();

            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("https://euw1.api.riotgames.com/lol/match/v4/matches/4695908702?api_key=" + ApiKey);

            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));

            HttpResponseMessage response = await client.GetAsync("https://euw1.api.riotgames.com/lol/match/v4/matches/" + matchId + "?api_key=" + ApiKey).ConfigureAwait(false);
            if (response.IsSuccessStatusCode)
            {
                dynamic jsonObject = await response.Content.ReadAsStringAsync();
                Root2 myDeserializedClass = JsonConvert.DeserializeObject<Root2>(jsonObject);

                for (int i = 0; i < 10; i++)
                {


                    teamChamptionItemList.Add(new championItemList()
                    {
                        item0 = myDeserializedClass.participants[i].stats.item0,
                        item1 = myDeserializedClass.participants[i].stats.item1,
                        item2 = myDeserializedClass.participants[i].stats.item2,
                        item3 = myDeserializedClass.participants[i].stats.item3,
                        item4 = myDeserializedClass.participants[i].stats.item4,
                        item5 = myDeserializedClass.participants[i].stats.item5,

                        Spell1Id = myDeserializedClass.participants[i].spell1Id,
                        Spell2Id = myDeserializedClass.participants[i].spell2Id,

                        Kills = myDeserializedClass.participants[i].stats.kills,
                        Death = myDeserializedClass.participants[i].stats.deaths,
                        Assist = myDeserializedClass.participants[i].stats.assists,
                        goldEarned = myDeserializedClass.participants[i].stats.goldEarned,
                        totalMinionsKilled = myDeserializedClass.participants[i].stats.totalMinionsKilled,
                        win = myDeserializedClass.participants[i].stats.win,
                        
                        

                    }); ;

                    if (teamChamptionItemList[i].win == true)
                    {
                        teamChamptionItemList[i].winStatus = "Victory";
                    }
                    else
                    {
                        teamChamptionItemList[i].winStatus = "Defeat";
                    }

                    TempList = await GetMatchSummonerSpells(teamChamptionItemList);
                    TempList[i].SummonerSpell1 = teamChamptionItemList[i].SummonerSpell1;
                    TempList[i].SummonerSpell2 = teamChamptionItemList[i].SummonerSpell2;

                    if (myDeserializedClass.participantIdentities[i].player.currentAccountId == accountId)  //Collects items from singel champion.
                    {

                        singelChampionItemList.Add(new championItemList()
                        {
                            item0 = teamChamptionItemList[i].item0,
                            item1 = teamChamptionItemList[i].item1,
                            item2 = teamChamptionItemList[i].item2,
                            item3 = teamChamptionItemList[i].item3,
                            item4 = teamChamptionItemList[i].item4,
                            item5 = teamChamptionItemList[i].item5,
                            summonerName = myDeserializedClass.participantIdentities[i].player.summonerName,

LeagueHistory/Controllers/SelectedMatchController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using LeagueHistory.Models;
using Newtonsoft.Json;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using RiotSharp;
using RiotSharp.Misc;
using System.Linq;
using LeagueHistory.Models.myClass;
using RiotSharp.Endpoints.SummonerEndpoint;

namespace LeagueHistory.Controllers
{
    public class SelectedMatchController : Controller
    {
        ApiStructure apiStructure = new ApiStructure();
        public static string[] champions = { "Aatrox","Olaf","Malzahar" ,"Ahri","Sylas","Sett", "Akali", "Lulu", "Alistar", "Amumu", "Annie", "Aphelios", "Ashe", "Janna","Thresh","Rammus","Darius","Ezreal",
            "Twitch","Udyr","Urgot","Varus","Vayne","Veigar","Velkoz","AurelionSol","Azir","Bard","Blitzcrank","Brand","Caitlyn","Camille","Cassiopeia","Chogath","Corki","Diana","DrMundo",
        "Ekko","Elise","Evelynn","Fiddlesticks","Fiora","Fizz","Galio","Gangplank","Garen","Gnar","Gragas","Graves","Hecarim","Heimerdinger","Illaoi","Irelia","JarvanIV","Jax","Jayce","Jhin",
        "Jinx","Kaisa","Kalista","Karma","Karthus","Kassadin","Nautilus","Nidalee","Kayn","Kennen","Khazix","Kindred","KogMaw","Leblanc","LeeSin","Leona","Lucian","Malphite","Maokai","MasterYi"
        ,"MissFortune","MonkeyKing","Morgana","Nami","Nasus","Shyvana","Jhin","Sion","Sivir","Skarner","Sona","Soraka","Swain","Syndra","TahmKench","Taliyah","Talon","Taric","Jhin","Teemo",
        "Tristana","Trundle","Tryndamere","Senna","TwistedFate","Pyke","Twitch","Viktor","Vladimir","Volibear","Vi","Warwick","Xayah","Xerath","XinZhao","Yasuo","Yorick","Yuumi","Zac","Zed","Lux","Ziggs",
        "Zilean","Zoe","Zyra"};

        public static string[] SummonerSpell = { "SummonerBarrier", "SummonerBoost", "SummonerDot", "SummonerExhaust", "SummonerFlash", "SummonerHaste", "SummonerHeal", "SummonerMana", "SummonerPoroRecall", "SummonerPoroThrow", "SummonerSmite", "SummonerSnowball", "SummonerTeleport" };



        // GET: SelectedMatch
        public async Task<ActionResult> Index(long gameid)
        {
          
            List<matchParticipant> funka1 = await GetMatchTeamParticipantsAsync(gameid);
            var brag = funka1;

            List<MyViewModel> viewModel = new List<MyViewModel>();

            viewModel.Add(new MyViewModel()
            {
                TheFirstTable = funka1
               
            });

            return View(viewModel);
        }

        public async Task<List<matchParticipant>> GetMatchTeamParticipantsAsync(long matchId)
        {
            var counter = 0;

            List<championItemList> teamParticipantsWin = new List<championItemList>();
            List<championItemList> teamParticipantsLose = new List<championItemList>();
            List<SumParticipant> participants = new List<SumParticipant>();
            List<matchParticipant> funka1 = new List<matchParticipant>();

            List<Timeline> hanam = new List<Timeline>();

            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("https://euw1.api.riotgames.com/lol/match/v4/matches/4695908702?api_key=" + apiStructure.GetApiRiot());

            client.DefaultRequestHeaders.Accept.Add(
            new MediaTypeWithQualityHeaderValue("application/json"));

            System.Threading.Thread.Sleep(100);
            HttpResponseMessage response = await client.GetAsync("https://euw1.api.riotgames.com/lol/match/v4/matches/" + matchId + "?api_key=" + apiStructure.GetApiRiot()).ConfigureAwait(false);

            if (response.IsSuccessStatusCode)
            {
                dynamic jsonObject = await response.Content.ReadAsStringAsync();
                Root2 myDeserializedClass = JsonConvert.DeserializeObject<Root2>(jsonObject);

                for (int i = 0; i < 10; i++)
                {

                    if (myDeserializedClass.participants[i].stats.win == true)
                    {
                        teamParticipantsWin.Add(new championItemList()
                        {
                            item0 = myDeserializedClass.participants[i].stats.item0,
                            item1 = myDeserializedClass.participants[i].stats.item1,
                            item2 = myDeserializedClass.participants[i].stats.item2,
                            item3 = myDeserializedClass.participants[i].stats.item3,
                            item4 = myDeserializedClass.participants[i].stats.item4,
                            item5 = myDeserializedClass.participants[i].stats.item5,

                            Spell1Id = myDeserializedClass.participants[i].spell1Id,
                            Spell2Id = myDeserializedClass.participants[i].spell2Id,

                            Kills = myDeserializedClass.participants[i].stats.kills,
                            Death = myDeserializedClass.participants[i].stats.deaths,
                            Assist = myDeserializedClass.participants[i].stats.assists,
                            goldEarned = myDeserializedClass.participants[i].stats.goldEarned,
                            totalMinionsKilled = myDeserializedClass.participants[i].stats.totalMinionsKilled,
                            win = myDeserializedClass.participants[i].stats.win,
                            summonerName = myDeserializedClass.participantIdentities[i].player.summonerName,
                        
                            
                             

                        }); ;


                    }
                    else
                    {

                        teamParticipantsLose.Add(new championItemList()
                        {
                            item0 = myDeserializedClass.participants[i].stats.item0,
                            item1 = myDeserializedClass.participants[i].stats.item1,
                            item2 = myDeserializedClass.participants[i].stats.item2,
                            item3 = myDeserializedClass.participants[i].stats.item3,
                            item4 = myDeserializedClass.participants[i].stats.item4,
                            item5 = myDeserializedClass.participants[i].stats.item5,

                            Spell1Id = myDeserializedClass.participants[i].spell1Id,
                            Spell2Id = myDeserializedClass.participants[i].spell2Id,

                            Kills = myDeserializedClass.participants[i].stats.kills,
                            Death = myDeserializedClass.participants[i].stats.deaths,
                            Assist = myDeserializedClass.participants[i].stats.assists,
                            goldEarned = myDeserializedClass.participants[i].stats.goldEarned,
                            totalMinionsKilled = myDeserializedClass.participants[i].stats.totalMinionsKilled,
                            win = myDeserializedClass.participants[i].stats.win,
                            summonerName = myDeserializedClass.participantIdentities[i].player.summonerName

                        }); ;
                    }
                }

                for (int g = counter; g < (teamParticipantsWin.Count()); g++)
                {
                    participants.Add(new SumParticipant() //Göra om så det blir två listor? eller ha dem i samma lsita?
                    {

                        teamParticipantWin = teamParticipantsWin[counter],
                        teamParticipantLose = teamParticipantsLose[counter],

                    });;

                    counter++;
                }

                funka1.Add(new matchParticipant()
                {
                    gameParticipants = participants           
                }) ; 
            }
            
            return funka1;
        }
    }
}

LeagueHistory/Views/Home/DisplayAccount.cshtml
@model  List<LeagueHistory.Models.myClass.MyViewModel>

@{

    Layout = "~/SharedLayout/_Header.cshtml";
}

<!DOCTYPE html>
<link href="~/Style/displayAccountStyle.css" rel="stylesheet" />
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DisplayAccount</title>
</head>
<body>

    <div>

        <div class="champBox">



            <div>



                @for (int i = 0; i < ViewBag.AmmountOfGames; i++)
                {
                    <div class="ChampionDisplay">

                        <div class="ChampionImg">
                            <a href="@Url.Action("Index", "SelectedMatch", new {  gameId = Model[0].TheSecondTable[i].gameId }, null)">
                                <img src="@Url.Content("http://ddragon.leagueoflegends.com/cdn/img/champion/loading/" + @Html.DisplayFor(x => Model[0].TheSecondTable[i].championName) + "_1.jpg")" alt="ChampionImg" />
                            </a>
                        </div>
                        <div class="Champion">

                            <div class="Champion-info1">
                                <div id="champTopAlign">
                                    <p class="champName">@Html.DisplayFor(x => Model[0].TheSecondTable[i].championName)</p>
                                    <p class="champUnderTitle">Blade runner</p>
                                </div>
                                <hr />
                                <div class="champQueLane">
                                    <div class="champQueHeader">
                                        <p>Queue</p>
                                        <p>Position</p>
                                    </div>
                                    <div>
                                        <p class="">@Html.DisplayFor(x => Model[0].TheSecondTable[i].role) </p>  @*why 0 on both? first i understand but why second?*@

                                        <p class="">  @Html.DisplayFor(x => Model[0].TheSecondTable[i].lane) </p>
                                    </div>

                                </div>

                                <div class="champImgInfo">
                                    <div class="champItems">
                                        <div class="champItemsDiv">
                                            @*<img src="imagenotfound.gif" alt="Image not found" onerror="this.onerror=null;this.src='imagefound.gif';" />*@
                                            <img src="@Url.Content("http://ddragon.leagueoflegends.com/cdn/10.14.1/img/item/"+Html.DisplayFor(x => Model[0].TheFirstTable[i].gameParticipants[0].singelParticipant.item0)+".png")" onerror="this.onerror=null;this.src='/Images/NoItem.png'" />
                                            <img src="@Url.Content("http://ddragon.leagueoflegends.com/cdn/10.14.1/img/item/"+Html.DisplayFor(x => Model[0].TheFirstTable[i].gameParticipants[0].singelParticipant.item1)+".png")" onerror="this.onerror=null;this.src='/Images/NoItem.png'" />
                                            <img src="@Url.Content("http://ddragon.leagueoflegends.com/cdn/10.14.1/img/item/"+Html.DisplayFor(x => Model[0].TheFirstTable[i].gameParticipants[0].singelParticipant.item2)+".png")" onerror="this.onerror=null;this.src='/Images/NoItem.png'" />

                                        </div>


                                        <div class="champItemsDiv">
                                            <img src="@Url.Content("http://ddragon.leagueoflegends.com/cdn/10.14.1/img/item/"+Html.DisplayFor(x => Model[0].TheFirstTable[i].gameParticipants[0].singelParticipant.item3)+".png")" onerror="this.onerror=null;this.src='/Images/NoItem.png'" />
                                            <img src="@Url.Content("http://ddragon.leagueoflegends.com/cdn/10.14.1/img/item/"+Html.DisplayFor(x => Model[0].TheFirstTable[i].gameParticipants[0].singelParticipant.item4)+".png")" onerror="this.onerror=null;this.src='/Images/NoItem.png'" ; />
                                            <img src="@Url.Content("http://ddragon.leagueoflegends.com/cdn/10.14.1/img/item/"+Html.DisplayFor(x => Model[0].TheFirstTable[i].gameParticipants[0].singelParticipant.item5)+".png")" onerror="this.onerror=null;this.src='/Images/NoItem.png'" ; />  @*onerror="this.onerror=null;this.src='/Images/NoItem.png'"; Defualt bild om inte hittat någon. Och så ingen oändlig loop.  *@

                                        </div>

                                    </div>


                                    <div class="champSumSpells">
                                        <div class="champSum">
                                            <img src="@Url.Content("http://ddragon.leagueoflegends.com/cdn/10.14.1/img/spell/"+ Html.DisplayFor(x => Model[0].TheFirstTable[i].gameParticipants[0].singelParticipant.SummonerSpell1)+".png")" />
                                        </div>
                                        <div class="champSum">
                                            <img src="@Url.Content("http://ddragon.leagueoflegends.com/cdn/10.14.1/img/spell/"+ Html.DisplayFor(x => Model[0].TheFirstTable[i].gameParticipants[0].singelParticipant.SummonerSpell2)+".png")" />

                                        </div>
                                    </div>


                                    <div class="champMasteries">
                                        <div class="champMastery">
                                            <img src="~/Images/mastery1.png" alt="Alternate Text" />
                                        </div>
                                        <div class="champMastery">
                                            <img src="~/Images/mastery2.png" alt="Alternate Text" />
                                        </div>
                                    </div>



                                </div>

                                <hr class="HrStyle" />

                                <div>
                                    <div>
                                        <p class="GameStats">Game Stats</p>
                                    </div>
                                    <div>
                                        @if (@Html.DisplayFor(x => Model[0].TheFirstTable[i].gameParticipants[0].singelParticipant.winStatus).ToString() == "Victory")
                                        {
                                            <p class="GameStatsWin">@Html.DisplayFor(x => Model[0].TheFirstTable[i].gameParticipants[0].singelParticipant.winStatus)</p>
                                        }
                                        else
                                        {
                                            <p class="GameStatsLose">@Html.DisplayFor(x => Model[0].TheFirstTable[i].gameParticipants[0].singelParticipant.winStatus)</p>
                                        }
                                    </div>

                                    <div class="IngameStats">


                                        <div class="KDAStats">
                                            <div class="KDAStatsImg">
                                                <img src="~/Images/KDA.png" alt="Alternate Text" />
                                            </div>
                                            <div class="KDA">
                                                <p>@Html.DisplayFor(x => Model[0].TheFirstTable[i].gameParticipants[0].singelParticipant.Kills) /</p>
                                                <p>@Html.DisplayFor(x => Model[0].TheFirstTable[i].gameParticipants[0].singelParticipant.Death) /</p>
                                                <p>@Html.DisplayFor(x => Model[0].TheFirstTable[i].gameParticipants[0].singelParticipant.Assist)</p>
                                            </div>
                                        </div>

                                        <div class="KDAStats">
                                            <div class="KDAStatsImg">
                                                <img src="~/Images/Minion.png" alt="Alternate Text" />
                                            </div>
                                            <div class="KDA">
                                                <p class="tet">@Html.DisplayFor(x => Model[0].TheFirstTable[i].gameParticipants[0].singelParticipant.totalMinionsKilled)</p>
                                            </div>
                                        </div>

                                        <div class="KDAStats">
                                            <div class="KDAStatsImg">
                                                <img src="~/Images/GoldEarned.png" alt="Alternate Text" />
                                            </div>
                                            <div class="KDA">
                                                <p class="tet">@Html.DisplayFor(x => Model[0].TheFirstTable[i].gameParticipants[0].singelParticipant.goldEarned)</p>
                                            </div>
                                        </div>

                                    </div>

                                </div>

                            </div>

                            @*@Html.DisplayFor(x => item.platformId)
                                @Html.DisplayFor(x => item.queue)
                                @Html.DisplayFor(x => item.season)
                                @Html.DisplayFor(x => item.timestamp)
                                @Html.DisplayFor(x => item.gameId)*@

                        </div>
                    </div>


                }


            </div>
        </div>





    </div>
</body>
</html>

LeagueHistory/Views/Home/Index.cshtml
<!DOCTYPE html>
@{

    Layout = "~/SharedLayout/_Header.cshtml";
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Style/LandingPage.css" rel="stylesheet" />
    <title>Index</title>
</head>
<body>
    <div class="MasterClass">
        <div class="FirstHalf">

            <div class="Title">

                <img src="~/Images/Line.png" alt="Alternate Text" />
                <p>League History</p>

            </div>

            <div class="SubHeading">
                <p>
                    Search for games and find out how well you did.
                    <br />
                    With
                    <span style="color: #11FFA7;">League History</span> you get a simpler and better analytic view of your games.
                </p>
            </div>

            <div>
                <img class="ChampionsDemo" src="~/Images/Champions.png" alt="Alternate Text" />
            </div>
        </div>

        <div class="SecondHalf">
            <div class="SecondDiv1">
                <img src="~/Images/Line2.png" alt="Alternate Text" />
            </div>
            <div  class="SecondDiv2">
                <div class="DivForm">
                    <p id="DivForm-P">Search for your game</p>
                    @using (Html.BeginForm("DisplayAccount", "Home"))
                    {
                        <p>@Html.TextBox("selectedRegion", null, new { placeholder = "Select Region", @class = "TextFormInput" })</p>
                        <p>@Html.TextBox("historyNumber", null, new { placeholder = "Select number of history", @class = "TextFormInput" })</p>
                        <p>@Html.TextBox("user", null, new { placeholder = "User name", @class = "TextFormInput" })</p> //, @class = "InlogForm"

                        <input type="submit" value="Search" class="SearchFormInput" />

                    }
                </div>
            </div>

        </div>


    </div>
</body>
</html>